import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
// page.js를 감싸는 파일
// <head> 태크 내용들을 여기에 적는다.
// 페이지 간에 공유하고 싶은 내용들 ( 상단메뉴 .. 등등)
